
version: "3.7"
services:
    client:
        build: ./client .
        restart: always
        image: client
        container_name: client
        ports:
            - "80:80"
        working_dir: /client/src/app
        volumes:
            - ./client:/client/src/app
        links:
            - api
    api:
        build: ./api .
        restart: always
        container_name: node-api
        ports:
            - "8080:8080"
        volumes:
            - ./api:/api
            - /api/node_modules